- WeClimb/View/MyPage/MyPageVC.swift
> 마이페이지 셀 버그 수정

- WeClimb.xcodeproj/project.pbxproj
- WeClimb/Model/FeedModel.swift
- WeClimb/View/LoginVC.swift
- WeClimb/View/MainFeed/MainFeedTabelCell.swift
- WeClimb/View/MainFeed/MainFeedVC.swift
> 메인피드 UI 수정, 로그인VC else문 삭제, configure 설정

- WeClimb.xcodeproj/project.pbxproj
- WeClimb/Common/ClimbingGymNameSpace.swift
- WeClimb/Common/Identifiers.swift
- WeClimb/Common/UploadNameSpace.swift
- WeClimb/Model/ClimbingGym.swift
- WeClimb/SceneDelegate.swift
- WeClimb/View/ClimbingGym/ClimbingDeatilGymVC.swift
- WeClimb/View/ClimbingGym/ClimbingGymInfoView.swift
- WeClimb/View/ClimbingGym/ClimbingGymVC.swift
- WeClimb/View/ClimbingGym/GymHeaderView.swift
- WeClimb/View/ClimbingGym/SectionDetailTableViewCell.swift
- WeClimb/View/ClimbingGym/SectionTableViewCell.swift
- WeClimb/View/Search/SearchVC.swift
- WeClimb/ViewModel/ClimbingDetailGymVM.swift
- WeClimb/ViewModel/ClimbingGymVM.swift
> ClimbingGym뷰 정보 탭 UI 및 다크모드 일부 적용

- WeClimb.xcodeproj/project.pbxproj
- WeClimb/Common/Enumeration.swift
- WeClimb/Common/FirebaseManager.swift
- WeClimb/View/LoginVC.swift
- WeClimb/View/SignUp/CreateNickNameVC.swift
- WeClimb/ViewModel/LoginVM.swift
중복이름 체크 메소드
계정 삭제 메소드
닉네임생성 후 확인버튼 누를 시 push 6~8번 되는 기묘한 현상 수정
> 파이어베이스 매니저 기능추가

- WeClimb/View/Feed/FeedView.swift
- WeClimb/View/Upload/UploadVC.swift
- WeClimb/ViewModel/UploadVM.swift
> 업로드 추가 버튼 예외 처리

- WeClimb/View/ClimbingGym/ClimbingGymVC.swift
- WeClimb/View/MyPage/SettingVC.swift
- WeClimb/View/MyPage/UserPageVC.swift
- WeClimb/View/Search/SearchVC.swift
> 세그먼트바에 맞는 화면 전환

- WeClimb/Common/FirebaseManager.swift
- WeClimb/Model/SearchModel.swift
- WeClimb/View/Search/SearchTableViewCell.swift
- WeClimb/View/Search/SearchVC.swift
- WeClimb/ViewModel/SearchVM.swift
> [Feat] 서치뷰 파이어베이스 연동로직

- WeClimb/Model/Gym.swift
- WeClimb/Model/SearchModel.swift
- WeClimb/View/ClimbingGym/ClimbingGymVC.swift
- WeClimb/View/Search/SearchTableViewCell.swift
- WeClimb/View/Search/SearchVC.swift
- WeClimb/ViewModel/SearchVM.swift
> [Refactor] 이상한 구조인 코드 발견 및 수정

- WeClimb/Common/UploadNameSpace.swift
- WeClimb/View/Feed/FeedCell.swift
- WeClimb/View/Feed/FeedView.swift
- WeClimb/View/Search/SearchVC.swift
- WeClimb/View/Upload/UploadOptionView.swift
- WeClimb/View/Upload/UploadVC.swift
- WeClimb/ViewModel/UploadVM.swift
- 업로드뷰에서 암장 선택 -> 서치뷰 모달
- 피드셀 잔버그 수정 
- 선택한 암장 기준으로 UIMenu 세팅
> [Feat] 업로드뷰 버그 수정 및 서치뷰 연결

- WeClimb.xcodeproj/project.pbxproj
- WeClimb/Common/FirebaseManager.swift
- WeClimb/View/MyPage/UserPageVC.swift
- WeClimb/View/Search/GymTableViewCell.swift
- WeClimb/View/Search/SearchVC.swift
- WeClimb/View/Search/UserTableViewCell.swift
- WeClimb/ViewModel/SearchVM.swift
> [Feat] 유저 검색기능 추가 및 파이어베이스 로직 추가

- WeClimb/Common/FirebaseManager.swift
- WeClimb/Model/Post.swift
- WeClimb/Model/User.swift
- WeClimb/ViewModel/LoginVM.swift
Feat: 특정 게시물의 댓글 가져오기, 피드 가져오기
Comment: Comment: FirebaseManager 들의 메소드들 주석 추가 및 수정
Refactor: User, Post, Comment의 각각 userUID, postUID, commentUID 추가 및 수정
> 파이어베이스매니저: 댓글 가져오기, 피드 가져오기

- WeClimb/Common/FirebaseManager.swift
- WeClimb/Model/Post.swift
- WeClimb/Model/User.swift
- WeClimb/ViewModel/LoginVM.swift
Feat: Post upload , Add Comment method
Refactor: Entity was refactored
User, Post, Comment
Feat: get all my posts , get feed first, loading
> 파베매니저 리팩토링

- WeClimb/Common/Enumeration.swift
- WeClimb/Common/FirebaseManager.swift
- WeClimb/Model/Post.swift
Refactor: Post, Comment like changed Int to [String]
좋아요 메소드
> Feat: like method, Like Enum added

- WeClimb/Common/FirebaseManager.swift
- WeClimb/Model/FeedCellModel.swift
- WeClimb/View/Feed/FeedCell.swift
- WeClimb/View/Feed/FeedView.swift
- WeClimb/View/Upload/UploadOptionView.swift
- WeClimb/View/Upload/UploadVC.swift
- WeClimb/ViewModel/UploadVM.swift
- 업로드뷰에서 옵션 UIMenu 예외 처리 및 버그 수정
- 파이어베이스 난이도, 섹션 옵셔널로 변경
- 게시 버튼 클릭시 서버 업로드
파이어베이스에 업로드된 결과입니다.
> [Feat] 업로드뷰 로직 구현

- WeClimb.xcodeproj/project.pbxproj
- WeClimb/Common/CommonManager.swift
- WeClimb/View/Upload/UploadVC.swift
- WeClimb/ViewModel/UploadVM.swift
- ios18버전 이상부터 미디어 재생 버그 수정
- 게시 후 UpLoadVC 초기화
- 취소 버튼 추가
- 알럿, 토스트 추가 및 공용 메서드
> 미디어 버그 수정 및 예외처리

- WeClimb/ViewModel/UploadVM.swift
> 취소 버튼 버그 수정

- WeClimb/View/MainFeed/SFMainFeedVC.swift
- WeClimb/View/Upload/UploadVC.swift
> [Fix] 업로드 버그 수정

- WeClimb/Common/FirebaseManager.swift
- WeClimb/Model/User.swift
- WeClimb/ViewModel/LoginVM.swift
> 차단 하기, 차단 풀기, 피드에서 차단된 계정 거르기

- WeClimb/View/LoginVC.swift
- WeClimb/View/SignUp/PrivacyPolicyVC.swift
- 회원가입시 이용약관 및 개인정보처리방침 추가 (클릭시 웹뷰로 이동)
- 로고 수정
> [Feat] 회원가입시 UI 및 기능 추가

- WeClimb.xcodeproj/project.pbxproj
- WeClimb/Common/SettingNameSpace.swift
- WeClimb/View/LoginVC.swift
- WeClimb/View/MyPage/MyPageVC.swift
- WeClimb/View/MyPage/SettingVC.swift
- WeClimb/View/Search/SearchVC.swift
- 암장/유저 검색 페이지 스크롤 시 키보드 숨김 처리 및 스크롤 고정 추가
- 프로필 편집 위치 이동(마이페이지 → 셋팅)
- 마이페이지 레벨/팔로우/팔로워 히든
- 마이페이지 키/암리치 UI 재설정 및 서버 정보 받아오기
- 로그인 버튼 위치 수정
38d1b64f-6565-4ff4-b962-4ce29d5dbbb2)
> [FEAT] 마이페이지, 암장세팅, 로그인 버튼 수정

- WeClimb.xcodeproj/project.pbxproj
- WeClimb/Common/SettingNameSpace.swift
- WeClimb/View/ClimbingGym/ClimbingGymVC.swift
- WeClimb/View/MainFeed/SFMainFeedVC.swift
- WeClimb/View/MyPage/BlackListCell.swift
- WeClimb/View/MyPage/BlackListVC.swift
- WeClimb/View/MyPage/MyPageVC.swift
- WeClimb/View/MyPage/SettingVC.swift
- WeClimb/View/MyPage/UserPageVC.swift
- WeClimb/View/Search/SearchVC.swift
- WeClimb/View/TabBarController.swift
- WeClimb/ViewModel/BlackListVM.swift
- WeClimb/ViewModel/UserPageVM.swift
차단기능 완벽구현은 아니지만 UI 업데이트를 위해 PR
> [Feat] 차단기능 및 UI 작업

- WeClimb/Common/SettingNameSpace.swift
- WeClimb/View/MyPage/SettingVC.swift
> [FEAT] 세팅 - 문의하기 기능 추가

- WeClimb.xcodeproj/project.pbxproj
- WeClimb/View/MainFeed/SFMainFeedVC.swift
- WeClimb/View/MyPage/EditNickNameVC.swift
- WeClimb/View/MyPage/EditPageVC.swift
- WeClimb/View/MyPage/MyPageVC.swift
- WeClimb/View/MyPage/SettingVC.swift
- WeClimb/View/MyPage/UserPageVC.swift
- WeClimb/View/Search/UserTableViewCell.swift
- WeClimb/View/TabBarController.swift
- 가로모드로 전환 금지
- 더보기 버튼 UI 수정
- 프로필 기본 이미지 추가
- 업로드뷰 비회원 처리
- 닉네임 편집시 실시간 반영
> [Feat] 미이페이지 기능 및 UI

- WeClimb/Common/FirebaseManager.swift
- WeClimb/Common/SettingNameSpace.swift
- WeClimb/View/ClimbingGym/ClimbingGymVC.swift
- WeClimb/View/ClimbingGym/GymHeaderView.swift
- WeClimb/View/MyPage/EditPageVC.swift
- WeClimb/View/MyPage/SettingVC.swift
- WeClimb/View/Search/GymTableViewCell.swift
- WeClimb/View/SignUp/CreateNickNameVC.swift
- WeClimb/ViewModel/SignUpVM/CreateNickNameVM.swift
> [Fix] 각종 짜잘짜잘한 버그 수정

- WeClimb.xcodeproj/project.pbxproj
- WeClimb/View/MainFeed/SFFeedCell.swift
> SFFeedCell이 KingFisher를 사용하게 변경

- WeClimb/Common/Enumeration.swift
- WeClimb/View/Upload/UploadVC.swift
Fix: 캡션쪽 입력을 하지 않았을때 플레이스홀더가 그대로 올라가는 오류, 미디어가 없을때도 업로드되는 오류
close #75 
> Fix: 캡션쪽 입력을 하지 않았을때 플레이스홀더가 그대로 올라가는 오류, 미디어가 없을때도 업로드되는 오류

- WeClimb/Common/Enumeration.swift
- WeClimb/Common/FirebaseManager.swift
- WeClimb/View/MainFeed/SFMainFeedVC.swift
- WeClimb/View/Upload/UploadVC.swift
- WeClimb/ViewModel/MainFeedVM.swift
close #72 
위로 스크롤 땡겼을때 리로드하게 만듬
> 메인피드 리로딩 기능

- WeClimb/View/MainFeed/SFCollectionViewCell.swift
- WeClimb/View/MainFeed/SFMainFeedVC.swift
close #73 
메인피드 미디어 스크롤, 로딩 인디케이터 medium to large
> [Fix] 메인피드에서 미디어 넘길시 제대로 안넘어가는 문제

- WeClimb/View/MainFeed/SFMainFeedVC.swift
- WeClimb/View/MyPage/MyPageVC.swift
- WeClimb/ViewModel/MainFeedVM.swift
- 마이페이지셀 클릭시 메인피드 셀로 화면전환
- 선택된 포스트부터 피드 시작
close #83 
https://github.com/user-attachments/assets/92ef716f-38ff-4a81-b27e-e3431c12717d
> [Feat] 마이페이지에서 메인 피드 셀 구성

- WeClimb.xcodeproj/project.pbxproj
- WeClimb/Common/ProfileManager.swift
- WeClimb/View/MyPage/EditPageVC.swift
- WeClimb/View/MyPage/MyPageVC.swift
- WeClimb/View/MyPage/ProfileImagePickerVC.swift
- WeClimb/View/SignUp/CreateNickNameVC.swift
- WeClimb/ViewModel/SignUpVM/CreateNickNameVM.swift
> [Feat] 프로필 이미지 추가 및 편집 기능

- WeClimb.xcodeproj/project.pbxproj
- WeClimb/Common/Enumeration.swift
- WeClimb/Common/FirebaseManager.swift
- WeClimb/Common/ProfileManager.swift
- WeClimb/Model/Post.swift
- WeClimb/View/MainFeed/SFCollectionViewCell.swift
- WeClimb/View/MainFeed/SFMainFeedVC.swift
- WeClimb/View/MyPage/EditPageVC.swift
- WeClimb/View/MyPage/MyPageCell.swift
- WeClimb/View/MyPage/MyPageVC.swift
- WeClimb/View/MyPage/ProfileImagePickerVC.swift
- WeClimb/View/SignUp/CreateNickNameVC.swift
- WeClimb/View/Upload/UploadVC.swift
- WeClimb/ViewModel/MainFeedVM.swift
- WeClimb/ViewModel/MyPageVM.swift
- WeClimb/ViewModel/SignUpVM/CreateNickNameVM.swift
- WeClimb/ViewModel/UploadVM.swift
> Fix: 업로드 조건 부족할때 알럿 안뜨는 오류
